# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('hash', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
