# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='hash',
        ),
        migrations.AddField(
            model_name='url',
            name='short',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
